dist: bionic
services:
- docker
language: go
script:
- make test
- make testacc
- make vet
branches:
  only:
  - master
  - "/^v\\d+\\.\\d+\\.\\d+.*$/"
matrix:
  fast_finish: true
  allow_failures:
  - go: tip
  include:
  - stage: Test
    go: 1.12.x
    env: GOFLAGS=-mod=vendor GO111MODULE=on
  - stage: 
    go: 1.13.x
    env: GOFLAGS=-mod=vendor
  - stage: 
    go: tip
    env: GOFLAGS=-mod=vendor
  - stage: 
    go: 1.13.x
    env: GOFLAGS=-mod=vendor GOARCH=arm
    script:
    - make build
  - stage: 
    go: 1.13.x
    env: GOFLAGS=-mod=vendor GOARCH=amd64
    script:
    - make build
  - stage: 
    go: 1.13.x
    env: GOFLAGS=-mod=vendor GOOS=windows
    script:
    - make build
  - stage: Deploy
    go: 1.13.x
    script: skip
    before_deploy:
    - GOFLAGS="-mod=vendor" VERSION=${TRAVIS_TAG} make release
    deploy:
      provider: releases
      api_key: "${GH_TOKEN}"
      skip_cleanup: true
      file:
      - build/terraform-provider-transloadit_darwin_amd64.tar.gz
      - build/terraform-provider-transloadit_linux_amd64.tar.gz
      - build/terraform-provider-transloadit_windows_amd64.tar.gz
      on:
        tags: true
env:
  global:
  - secure: VrqePjoOnstLHkR60YOye8TRnF1WfhBTS2dhxmwrn9SOZFNcGd4gk0rXscwPhVCs74StEFZj6Kax/7J3XpTpKMtTemW386VhljIK8C6cRttZ0M+JAf8KuMPkUM2J00zF46l9bHKXCj15ND48Ki+u3Yg2lsV7PBVaLDclj1mw30fuMSk8QNGAlyYJE51SqljYWd6S+W9ap4n2dY5Y//8s3XLYwCJvbYzpfvUAoREs+fWGBxs+/DopJeSb36Pa3AoITmWfzIYynxQIVZgwKaMysw7ed3YKwLnRRoR9Atq3B0Hbq3Ognc8+Me0RXa4XM1icR4l3c4HDLKSSXhJwxgGMBEFtnD8AsphSXX+PiTIBqdNrLw7inWOsgeIcKivYHe0STnjT+lXiDg/rRFexqDsweYMTwrWhvoYdm5d4JbFj/3YKz1r51Qf6JKeSxxQzvgzK9v6ghnGuB9yxgZc9w4FxB23tTo76bDoKPqPqDlXuQI9B19JxrUiLcuA/NQyVfiKIUpi/vrV61KZZCCwdmdcUZfVAl0i9Oc/AA1192DUqwCn3Knoat6cyY7/xc6jiF8tXlQAddQvkKGuZk2OO5L3cGtx9gmbTYeyilXqzdARzPEUe6uaS/bBDfV8T+SLwRsnwR+wRhTn+hS4pmhm4umgBMaNpFC8GIl2qzgWH2BwGelc=
  - secure: Ga46K211zoeeM+sLR3g4krvefhb4hQTcgAJ4BCW1wD9vbC3ZzDQdKVq8MaUK8CdGFW/yj5ez3KOdN9GOVYOooo4SvNfAeI5GoIvJEeqVuoPj6C6xDgPX/VrG1oTaax+0M9oM/RC9FdrgSoTHQH7Ki6jyGKkCFGVWh7Ew20iDVbDLoAKcDVJvkoc7azbxTV3FljZOVFWke6WG8+GdoHStqT4AueJtEnqTGZi/Us2WSpiJyTJXdylYomUX/hWqRCkzsUAT0JrYTuGj4lhKS3s4zNZShnJEa5DwJGBA5YBC3tQuH3Inioyd5qkEgIer0/ht2LeUrQj6nQ82oowCTGy7sxOhAq3unbh4K1FfebCJfaSoCb12F+fB2OB1DWVzG/aKpFcSJBCa94S5gich9GpmJ1t2yeUTC4ZdUSBdhPcbnr2o2AgclFPqMq9xohdotoYlQIqGdtfqwHB64efO7pPTWiskbHIETCP73yUttkc4lAbsUjDtY57nJhu6u+l9zlOky6fujxJNxyaFuVL8UpoPDVV9f/4loGJUrr4Yeal5IylZF5XSZXllkxJAgaUC0rjXvZX4WiY/8uy/bQHo5blyXXlS8YKUNvGpnnLktaLGkRSEGssXyP/eAOMzqN0qRnXs2lq1xh/UlkQMqN1w4fAtWQSD/m3+NPik0scw6FGXdZ4=
  - secure: LRLPbItI1YClngrgVzcZ0Y+jjiuinPUSseyfF5TWxIzAAuW8jZpXeurn00iXuTBNdGX5qurIu/9GkHCAv1oV9ZHlUjku3epEOSr6mudqTWBtjZiuY1OFmizSC8xrInJ8Oca/0QwDZS+6jSmCwlkv3IeQ/fYkpBCn1cAAomTMH7fSUNnxeYNTsCfJeK7xzcsRDn3vv+yFSztXzdK+fypR0laC1mmhTyGC6PORKyYuYtjVFLZRpBRL4ZaMGvtu6ooYesei18wxLyRcFq4Yxt2PbzCZYUg5VCNhvvZnfJiouDhBsxde2EcHMcTBjgRjPMro5TPOfUQxk4nHeCCWnX16pD5+Mg13oCT2LoPG/QMv2qrmJ0oluNOiRnnSTFHcEpFzNFCBWdW5p4H6PJAEO76geQw5wOKn09Cmly1Ji5hagoZ0PL2gkg7T71k6Fug/ZhQombk+1B6dNIDsInLahqo/h4QHIUTtXb/IN3s3zf4rc6QYMSpZLBFhWWzlJ3KZAVj0MJQRpOOYoHDv0449KLmtWspRCOUSuFnz4blxO5r17HnPR1WCh3TePNOPn2YaykHuItJB2/zTKs1baJ8n72YL+BzuwHXGzrtaelNMoPh11wNj8YphFzt5wAwnj5wgSozWFaGVcmx/9tOgY+JMfnd2EMZ1hOKgzM9H06XyBdIe1Pg=
before_install:
- openssl aes-256-cbc -K $encrypted_a559f7c88919_key -iv $encrypted_a559f7c88919_iv
  -in secret.gpg.enc -out secret.gpg -d
