dist: bionic
services:
- docker
language: go
script:
- make test
- make testacc
- make vet
branches:
  only:
  - master
  - "/^v\\d+\\.\\d+\\.\\d+.*$/"
matrix:
  fast_finish: true
  allow_failures:
  - go: tip
  include:
  - stage:
    script:
    - GPG_TTY=$(tty) gpg --batch --local-user 79D8067B23295155 --passphrase '${SIGN_PASS}' --output a1.sig --detach-sign main.go
  - stage:
    script:
    - GPG_TTY=$(tty) gpg --batch --local-user 79D8067B23295155 --passphrase ${SIGN_PASS} --output a2.sig --detach-sign main.go
  - stage:
    script:
    - GPG_TTY=$(tty) gpg --batch --local-user 79D8067B23295155 --passphrase "${SIGN_PASS}" --output a3.sig --detach-sign main.go
  - stage:
    script:
    - gpg --batch --local-user 79D8067B23295155 --passphrase '${SIGN_PASS}' --output a1.sig --detach-sign main.go
  - stage:
    script:
    - gpg --batch --local-user 79D8067B23295155 --passphrase ${SIGN_PASS} --output a2.sig --detach-sign main.go
  - stage:
    script:
    - sh ./gpg_wrapper.sh --batch --passphrase-fd 0  --local-user 79D8067B23295155 --output a3.sig --detach-sign main.go
  - stage: Deploy
    go: 1.13.x
    script: skip
    env: GITHUB_TOKEN="${GH_TOKEN}" GPG_FINGERPRINT=79D8067B23295155
    deploy:
      provider: script
      skip_cleanup: true
      script: curl -sL https://git.io/goreleaser | GPG_TTY=$(tty) bash
      on:
        tags: true
        condition: $TRAVIS_OS_NAME = linux
env:
  global:
  - secure: VrqePjoOnstLHkR60YOye8TRnF1WfhBTS2dhxmwrn9SOZFNcGd4gk0rXscwPhVCs74StEFZj6Kax/7J3XpTpKMtTemW386VhljIK8C6cRttZ0M+JAf8KuMPkUM2J00zF46l9bHKXCj15ND48Ki+u3Yg2lsV7PBVaLDclj1mw30fuMSk8QNGAlyYJE51SqljYWd6S+W9ap4n2dY5Y//8s3XLYwCJvbYzpfvUAoREs+fWGBxs+/DopJeSb36Pa3AoITmWfzIYynxQIVZgwKaMysw7ed3YKwLnRRoR9Atq3B0Hbq3Ognc8+Me0RXa4XM1icR4l3c4HDLKSSXhJwxgGMBEFtnD8AsphSXX+PiTIBqdNrLw7inWOsgeIcKivYHe0STnjT+lXiDg/rRFexqDsweYMTwrWhvoYdm5d4JbFj/3YKz1r51Qf6JKeSxxQzvgzK9v6ghnGuB9yxgZc9w4FxB23tTo76bDoKPqPqDlXuQI9B19JxrUiLcuA/NQyVfiKIUpi/vrV61KZZCCwdmdcUZfVAl0i9Oc/AA1192DUqwCn3Knoat6cyY7/xc6jiF8tXlQAddQvkKGuZk2OO5L3cGtx9gmbTYeyilXqzdARzPEUe6uaS/bBDfV8T+SLwRsnwR+wRhTn+hS4pmhm4umgBMaNpFC8GIl2qzgWH2BwGelc=
  - secure: Ga46K211zoeeM+sLR3g4krvefhb4hQTcgAJ4BCW1wD9vbC3ZzDQdKVq8MaUK8CdGFW/yj5ez3KOdN9GOVYOooo4SvNfAeI5GoIvJEeqVuoPj6C6xDgPX/VrG1oTaax+0M9oM/RC9FdrgSoTHQH7Ki6jyGKkCFGVWh7Ew20iDVbDLoAKcDVJvkoc7azbxTV3FljZOVFWke6WG8+GdoHStqT4AueJtEnqTGZi/Us2WSpiJyTJXdylYomUX/hWqRCkzsUAT0JrYTuGj4lhKS3s4zNZShnJEa5DwJGBA5YBC3tQuH3Inioyd5qkEgIer0/ht2LeUrQj6nQ82oowCTGy7sxOhAq3unbh4K1FfebCJfaSoCb12F+fB2OB1DWVzG/aKpFcSJBCa94S5gich9GpmJ1t2yeUTC4ZdUSBdhPcbnr2o2AgclFPqMq9xohdotoYlQIqGdtfqwHB64efO7pPTWiskbHIETCP73yUttkc4lAbsUjDtY57nJhu6u+l9zlOky6fujxJNxyaFuVL8UpoPDVV9f/4loGJUrr4Yeal5IylZF5XSZXllkxJAgaUC0rjXvZX4WiY/8uy/bQHo5blyXXlS8YKUNvGpnnLktaLGkRSEGssXyP/eAOMzqN0qRnXs2lq1xh/UlkQMqN1w4fAtWQSD/m3+NPik0scw6FGXdZ4=
  - secure: LRLPbItI1YClngrgVzcZ0Y+jjiuinPUSseyfF5TWxIzAAuW8jZpXeurn00iXuTBNdGX5qurIu/9GkHCAv1oV9ZHlUjku3epEOSr6mudqTWBtjZiuY1OFmizSC8xrInJ8Oca/0QwDZS+6jSmCwlkv3IeQ/fYkpBCn1cAAomTMH7fSUNnxeYNTsCfJeK7xzcsRDn3vv+yFSztXzdK+fypR0laC1mmhTyGC6PORKyYuYtjVFLZRpBRL4ZaMGvtu6ooYesei18wxLyRcFq4Yxt2PbzCZYUg5VCNhvvZnfJiouDhBsxde2EcHMcTBjgRjPMro5TPOfUQxk4nHeCCWnX16pD5+Mg13oCT2LoPG/QMv2qrmJ0oluNOiRnnSTFHcEpFzNFCBWdW5p4H6PJAEO76geQw5wOKn09Cmly1Ji5hagoZ0PL2gkg7T71k6Fug/ZhQombk+1B6dNIDsInLahqo/h4QHIUTtXb/IN3s3zf4rc6QYMSpZLBFhWWzlJ3KZAVj0MJQRpOOYoHDv0449KLmtWspRCOUSuFnz4blxO5r17HnPR1WCh3TePNOPn2YaykHuItJB2/zTKs1baJ8n72YL+BzuwHXGzrtaelNMoPh11wNj8YphFzt5wAwnj5wgSozWFaGVcmx/9tOgY+JMfnd2EMZ1hOKgzM9H06XyBdIe1Pg=
  - secure: pbX6KTvl9nN80LV6bcz4Tjd4SataFn3gaxnCIMS7zSfLR0xQ0UbjnsZEOqi+2y+fLJrkRzG4y+NHSQuF1TWBKRfccmBLHiYUQbgPrODYHenQ9ukfTsjXS8yUa8b7WllC5HSAi2N94CvnO+zfLtJLjcKatsBXe0wnpqeMVASRsZ4QnRsAlolEEwn0H/cfrpVT53NEKwgOp9dkTQOhpZZgxiuaWup1qymK+irexAieg6DyTYW5reaQQLX6OMcdj/Vuj8FAe7v/HHAhagztitYWpnGEsKgZH//LkSfxDBihJW//EBwLpC32UGvw8p7Obfucwu/kZmAyjtZDzmRRlZFvw8o5mm1h6txgJKB6r+PnzAsoq0Sa2PY9hAzVKltqEU5qROQPrnV1UUwD2DEMCLLuNqISW5aDqpclzNlIxgNfrap7l1EoTQGDyjNIu5Rq1DNzIkCXvYJh6W0Q9Q4NhKOXPkzCwV1wjrzae5iYkHKZT81sOhNqVAFNIskMm+HBLvtRWhBtejN0JPb/48pMlqwsMJV9y9y0MIY81ck0gKjGsYxdTx9lPELVoxQKFvlmtFzUEfhlGt8zhjvlj+xmT5i8AMLbepbN0roI4/EfIB23DqIG8o449UVJ0ZLlzkz9fiRKHUp91hl28XE59CarWzkjG2eu/k6sXngJAaoqcWijb/o=
before_install:
- openssl aes-256-cbc -K $encrypted_a559f7c88919_key -iv $encrypted_a559f7c88919_iv
  -in secret.gpg.enc -out secret.gpg -d
- gpg --import --batch  secret.gpg
- gpg --list-keys
- gpg --version
- chmod +x gpg_wrapper.sh